### PR TITLE
Add working-directory input to golang-ci

### PR DESCRIPTION
**Pull request by mmcgehee-ccc**

### CODE REVIEW

**Comment by jwatson-ccc** [comment]
I am curious about the background of these settings. Why are they needed?

**Comment by mmcgehee-ccc** [comment]
> I am curious about the background of these settings. Why are they needed?

For a project where the go-related files are in a sub directory. For example, the [OCR app](https://github.com/cccteam/nes-ocr-app).

**Comment by jwatson-ccc** [comment]
> > I am curious about the background of these settings. Why are they needed?
> 
> For a project where the go-related files are in a sub directory. For example, the [OCR app](https://github.com/cccteam/nes-ocr-app).

Okay, perfect! And with the default value `.`, there is no need to specify for our other projects.

**Review by zredinger-ccc — APPROVED** [review]
LGTM

**Pull request merged**
