### PR TITLE
fix: Retrieve Go version from go mod file for govulncheck

### LINKED ISSUE #29: Security scanning of "latest release" uses incorrect go version
The go version defined on the main branch is used (for govulncheck) rather than the version defined in the latest release.

### PR DESCRIPTION
**Pull request by mmcgehee-ccc**
closes #29

### CODE REVIEW

**Comment by mmcgehee-ccc** [comment]
@jwatson-ccc 
I tested this here: https://github.com/cccteam/logger/actions/runs/9451760603

**Review by athomas-ccc — COMMENTED** [review]
@mmcgehee-ccc this looks great! By viewing the linked issue, I believe I understand the context of why this change is being made, as well. One question before I approve - can you comment on why the testing shows a status of Failure? I'm assuming it's a situation, perhaps, where failure was expected? 

https://github.com/cccteam/logger/actions/runs/9451760603

**Comment by mmcgehee-ccc** [comment]
> @mmcgehee-ccc this looks great! By viewing the linked issue, I believe I understand the context, as well. One question before I approve - can you comment on why the testing shows a status of Failure? I'm assuming it's a situation, perhaps, where failure was expected?
> 
> https://github.com/cccteam/logger/actions/runs/9451760603

Good question -- yes, failure was expected here because the latest release used Go 1.22.3 vs 1.22.4 used on the main/master branch.  Go 1.22.3 includes a vulnerability, which govulncheck was finding.

**Comment by jwatson-ccc** [comment]
> @mmcgehee-ccc this looks great! By viewing the linked issue, I believe I understand the context, as well. One question before I approve - can you comment on why the testing shows a status of Failure? I'm assuming it's a situation, perhaps, where failure was expected?
> 
> https://github.com/cccteam/logger/actions/runs/9451760603

@athomas-ccc 

This bug was discovered when govulncheck reported the issue referenced in the failed ci run above. When the master branch was fixed, we expected the current release version (v0.1.9) would still show this this vulnerability, but it didn't. Once Mack put in this fix, it is now properly failing on v0.1.9.

**Review by jwatson-ccc — APPROVED** [review]
LGTM

**Pull request merged**
