### PR TITLE
Revert "chore(main): release 3.0.1 (#31)"

### PR DESCRIPTION
**Pull request by mmcgehee-ccc**
This reverts commit 8e165bd7658e342e1c0412f9b0ae672e6b63fdf5.

### CODE REVIEW

**Comment by mmcgehee-ccc** [comment]
I don't see support for release deprecation in GitHub... I think this is the best path forward:
- Delete the release (already done)
- Revert the release PR (here)
- Delete the tag for the release

**Comment by athomas-ccc** [comment]
This is what AI had to say about options:
>As of my last update, GitHub does not provide a built-in feature specifically for deprecating a release. Releases are tied to tags in your repository, and while you can delete or edit a release, there isn't a formal "deprecate" status you can apply to it. However, you can effectively communicate the deprecation of a release to your users through the following methods:
>1. Edit the Release Notes: Go to the release you want to deprecate, click "Edit," and prepend a deprecation notice at the top of the release notes. Clearly state that the release is deprecated, and if applicable, provide guidance on which version users should migrate to.
Example notice:
```
## Deprecated
This release has been deprecated. Please use version x.y.z instead.
```

>2. Pre-Release Tag: If the release hasn't been widely used or you caught the issue early, you could mark the release as a "Pre-release" in GitHub. This doesn't deprecate it per se but signals to users that it might not be ready for production use, which could serve a similar purpose depending on your situation.
>3. Delete the Release: If the release has critical issues and you want to prevent any further usage, you can delete the release. However, this action does not delete the git tag associated with the release, so you might also want to delete or move the tag. Be cautious with this approach, as it could impact users who depend on that release.
>4. Communicate Outside of GitHub: Use your project's mailing list, blog, or other communication channels to inform users of the deprecation. This can be an effective way to reach users who might not check the GitHub releases page.
>5. GitHub Discussions or Issues: Utilize GitHub Discussions or Issues to announce the deprecation and discuss it with your community. This can also be a place for users to ask questions and get support for migrating to a newer version.

@mmcgehee-ccc what are your thoughts on marking it as a pre-release (suggestion 2), or simply editing the release notes (suggestion 1)?

**Comment by mmcgehee-ccc** [comment]
@athomas-ccc 
Since it was just released today and shouldn't be in use anywhere yet, I prefer the approach of just deleting the release (option 3)...  We don't really have a choice since I already deleted the release (prior to our dev meeting) and this action can't be undone  :slightly_smiling_face:

**Review by athomas-ccc — APPROVED** [review]
Makes sense! Thanks, Mack! Looks good.

**Pull request merged**
